name: GitHub Actions okCredit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
#       - name: Upload File to Headspin
#         run: | 
#           curl --location --request POST 'https://27516e17e00845e888663172623e9ea5@api-dev.headspin.io/v0/apps/apk/upload' \ --header 'Content-Type: application/vnd.android.package-archive' \--data-binary '@okc.apk'
      
       - name: Get apk package names
         run: | 
           curl https://fa5a3d68c9ee40a0911454fabb76db3d@api-dev.headspin.io/v0/apps/apk/packages
           
      - uses: actions/checkout@v2
     
      
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.data }}
