name: GitHub Actions okCredit
on: 
  push:
    branches: [ main ]
  
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Upload File to Headspin
        run: | 
          ls -l
          pwd
          
      - name: Get apk package names
        run: | 
            curl https://fa5a3d68c9ee40a0911454fabb76db3d@api-dev.headspin.io/v0/apps/apk/packages
           
      - uses: actions/checkout@v2
     
      
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.data }}
